import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

/** Merges Tailwind class names, letting later classes win over conflicting earlier ones. */
export const Cn = (...inputs: ClassValue[]) => twMerge(clsx(inputs));

/** Lower-case alias: components generated by the shadcn CLI import `cn`. */
export const cn = Cn;
